Total_population INT, Male INT, Female INT, Under_5_years INT, 5_to_9_years INT, 
10_to_14_years INT, 15_to_19_years INT, 20_to_24_years INT, 25_to_34_years INT, 
35_to_44_years INT, 45_to_54_years INT, 55_to_59_years INT, 60_to_64_years INT, 
65_to_74_years INT, 75_to_84_years INT, 85_years_and_over INT, Median_age_years FLOAT, 
18_years_and_over INT, 65_years_and_over INT, One_race INT, White INT, 
Black_or_African_American INT, American_Indian_and_Alaska_Native INT, Asian INT, 
Native_Hawaiian_and_Other_Pacific_Islander INT, Some_other_race INT, 
Two_or_more_races INT, Hispanic_or_Latino_of_any_race INT, Mexican INT, 
Puerto_Rican INT, Cuban INT, Other_Hispanic_or_Latino INT, 
Not_Hispanic_or_Latino INT, Native INT, Born_in_United_States INT, 
State_of_residence INT, Different_state INT, 
Born_in_Puerto_Rico__U.S._Island_areas__or_born_abroad_to_American_parents INT, 
Foreign_born INT, American INT, Arab INT, Czech INT, Danish INT, Dutch INT, English INT, 
French_except_Basque INT, French_Canadian INT, German INT, Greek INT, Hungarian INT, 
Irish INT, Italian INT, Lithuanian INT, Norwegian INT, Polish INT, Portuguese INT, 
Russian INT, ScotchIrish INT, Scottish INT, Slovak INT, Subsaharan_African INT, 
Swedish INT, Swiss INT, Ukrainian INT, Welsh INT, 
West_Indian_excluding_Hispanic_origin_groups INT, 
Civilian_population_18_years_and_over INT, Civilian_veterans INT, 
Total_civilian_noninstitutionalized_population INT, With_a_disability INT, 
Under_18_years INT, With_a_disability INT, 18_to_64_years INT, With_a_disability INT, 
65_years_and_over INT, With_a_disability INT, Population_1_year_and_over INT, 
Same_house INT, Different_house_in_the_U.S. INT, Same_county INT, 
Different_county INT, Same_state INT, Different_state INT, Abroad INT, 
Population_16_years_and_over INT, In_labor_force INT, Civilian_labor_force INT, 
Employed INT, Unemployed INT, Armed_Forces INT, Not_in_labor_force INT, 
Unemployment_Rate FLOAT, Workers_16_years_and_over INT, 
Car__truck__or_van__drove_alone INT, Car__truck__or_van__carpooled INT, 
Public_transportation_excluding_taxicab INT, Walked INT, Other_means INT, 
Worked_at_home INT, Mean_travel_time_to_work_minutes FLOAT, 
Management__business__science__and_arts_occupations INT, 
Service_occupations INT, Sales_and_office_occupations INT, 
Natural_resources__construction__and_maintenance_occupations INT, 
Production__transportation__and_material_moving_occupations INT, 
Agriculture__forestry__fishing_and_hunting__and_mining INT, Construction INT, 
Manufacturing INT, Wholesale_trade INT, Retail_trade INT, 
Transportation_and_warehousing__and_utilities INT, Information INT, 
Finance_and_insurance__and_real_estate_and_rental_and_leasing INT, 
Professional__scientific__and_management__and_administrative_and_waste_management_services INT, 
Educational_services__and_health_care_and_social_assistance INT, 
Arts__entertainment__and_recreation__and_accommodation_and_food_services INT, 
Other_services__except_public_administration INT, Public_administration INT, 
Private_wage_and_salary_workers INT, Government_workers INT, 
Selfemployed_in_own_not_incorporated_business_workers INT, 
Unpaid_family_workers INT, Total_housing_units INT, Occupied_housing_units INT, 
Vacant_housing_units INT, Homeowner_vacancy_rate FLOAT, Rental_vacancy_rate FLOAT, 
Owneroccupied INT, Renteroccupied INT, 
Average_household_size_of_owneroccupied_unit FLOAT, 
Average_household_size_of_renteroccupied_unit FLOAT, Moved_in_2015_or_later INT, 
Moved_in_2010_to_2014 INT, Moved_in_2000_to_2009 INT, Moved_in_1990_to_1999 INT, 
Moved_in_1980_to_1989 INT, Moved_in_1979_and_earlier INT, Less_than_50_000 INT, 
50_000_to_99_999 INT, 100_000_to_149_999 INT, 150_000_to_199_999 INT, 
200_000_to_299_999 INT, 300_000_to_499_999 INT, 500_000_to_999_999 INT, 
1_000_000_or_more INT, Median_dollars INT, Housing_units_with_a_mortgage INT, 
Housing_units_without_a_mortgage INT, Less_than_500 INT, 500_to_999 INT, 
1_000_to_1_499 INT, 1_500_to_1_999 INT, 2_000_to_2_499 INT, 2_500_to_2_999 INT, 
3_000_or_more INT, Median_dollars INT, Less_than_250 INT, 250_to_399 INT, 
400_to_599 INT, 600_to_799 INT, 800_to_999 INT, 1_000_or_more INT, Median_dollars INT, 
Occupied_units_paying_rent INT, Less_than_500 INT, 500_to_999 INT, 
1_000_to_1_499 INT, 1_500_to_1_999 INT, 2_000_to_2_499 INT, 2_500_to_2_999 INT, 
3_000_or_more INT, Median_dollars INT, No_rent_paid INT, Less_than_10_000 INT, 
10_000_to_14_999 INT, 15_000_to_24_999 INT, 25_000_to_34_999 INT, 
35_000_to_49_999 INT, 50_000_to_74_999 INT, 75_000_to_99_999 INT, 
100_000_to_149_999 INT, 150_000_to_199_000 INT, 200_000_or_more INT, 
Median_household_income_dollars INT, Mean_household_income_dollars INT, 
With_health_insurance_coverage INT, With_private_health_insurance INT, 
With_public_coverage INT, No_health_insurance_coverage INT, 
Civilian_noninstitutionalized_population_under_19_years INT, 
No_health_insurance_coverage INT, All_families FLOAT, 
With_related_children_of_the_householder_under_18_years INT, 
With_related_children_of_the_householder_under_5_years_only INT, 
Married_couple_families INT, 
With_related_children_of_the_householder_under_18_years INT, 
With_related_children_of_the_householder_under_5_years_only INT, 
Families_with_female_householder__no_husband_present INT, 
With_related_children_of_the_householder_under_18_years INT, 
With_related_children_of_the_householder_under_5_years_only INT, 
All_people INT, Under_18_years INT, 
Related_children_of_the_householder_under_18_years INT, 
Related_children_of_the_householder_under_5_years INT, 
Related_children_of_the_householder_5_to_17_years INT, 18_years_and_over INT, 
65_years_and_over INT, People_in_families INT, 
Unrelated_individuals_15_years_and_over INT, 
Population_3_years_and_over_enrolled_in_school INT, 
Nursery_school__preschool INT, Kindergarten INT, Elementary_school_grades_18 INT, 
High_school_grades_912 INT, College_or_graduate_school INT, 
Population_25_years_and_over INT, Less_than_9th_grade INT, 
9th_to_12th_grade__no_diploma INT, 
High_school_graduate_includes_equivalency INT, Some_college__no_degree INT, 
Associate_s_degree INT, Bachelor_s_degree INT, 
Graduate_or_professional_degree INT, 
Percent_high_school_graduate_or_higher FLOAT, 
Percent_bachelor_s_degree_or_higher FLOAT, Title INT, Total_for_all_sectors INT, 
Agriculture__forestry__fishing_and_hunting INT, 
Mining__quarrying__and_oil_and_gas_extraction INT, Utilities INT, 
Construction INT, Manufacturing INT, Wholesale_trade INT, Retail_trade INT, 
Transportation_and_warehousing INT, Information INT, Finance_and_insurance INT, 
Real_estate_and_rental_and_leasing INT, 
Professional__scientific__and_technical_services INT, 
Management_of_companies_and_enterprises INT, 
Administrative_and_support_and_waste_management_and_remediation_services INT, 
Educational_services INT, Health_care_and_social_assistance INT, 
Arts__entertainment__and_recreation INT, Accommodation_and_food_services INT, 
Other_services_except_public_administration INT, Industries_not_classified INT, 
Total_for_all_sectors INT, Agriculture__forestry__fishing_and_hunting INT, 
Mining__quarrying__and_oil_and_gas_extraction INT, Utilities INT, 
Construction INT, Manufacturing INT, Wholesale_trade INT, Retail_trade INT, 
Transportation_and_warehousing INT, Information INT, Finance_and_insurance INT, 
Real_estate_and_rental_and_leasing INT, 
Professional__scientific__and_technical_services INT, 
Management_of_companies_and_enterprises INT, 
Administrative_and_support_and_waste_management_and_remediation_services INT, 
Educational_services INT, Health_care_and_social_assistance INT, 
Arts__entertainment__and_recreation INT, Accommodation_and_food_services INT, 
Other_services_except_public_administration INT, Industries_not_classified INT, 
Total_for_all_sectors INT, Agriculture__forestry__fishing_and_hunting INT, 
Mining__quarrying__and_oil_and_gas_extraction INT, Utilities INT, 
Construction INT, Manufacturing INT, Wholesale_trade INT, Retail_trade INT, 
Transportation_and_warehousing INT, Information INT, Finance_and_insurance INT, 
Real_estate_and_rental_and_leasing INT, 
Professional__scientific__and_technical_services INT, 
Management_of_companies_and_enterprises INT, 
Administrative_and_support_and_waste_management_and_remediation_services INT, 
Educational_services INT, Health_care_and_social_assistance INT, 
Arts__entertainment__and_recreation INT, Accommodation_and_food_services INT, 
Other_services_except_public_administration INT, Industries_not_classified INT, 
state_dist INT, 